### ISSUE TITLE
Add info about our local Docker Hub mirror

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#231]
We recently introduced a Docker Hub mirror which runs inside the same DC as all Semaphore jobs. This should be prominently visible on the "Working with Docker" page.

For comparison, Google Cloud's docs about their DH mirror: [link](https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring).

**Comment by schliflo** [comment]
Hi @markoa I found this issue when investigating why I'm getting `ff3a5c916c92: Retrying in 20 seconds` messages when pulling images in CI jobs. I found out about the undocumented internal semaphore mirror by digging into the config...

Some questions: 
- Why am i getting these "retrying" messages? Is there some sort of rate limiting?
- Why would it be better to use the semaphore mirror rather than googles? Latency/Availability/Speed?

**Comment by bogyo210** [comment]
Hi @schliflo,
Please let me answer Your questions:

These "retrying" messages can manifest when a docker registry proxy doesn't have the image requested and is working on fetching it before serving it or the docker registry for some other reason cannot serve the request at the moment.

If you find that "retrying" message on several occasions please submit a support request.

**Comment by schliflo** [comment]
I ran into the `Retrying` message multiple times before. We use custom images (which are pre-built & published to DockerHub) in our CI jobs. 
The issue seems to be solved by using the google proxy:
```bash
sudo sed -i 's@https://dockerhub.semaphoreci.com/@https://mirror.gcr.io@g' /etc/docker/daemon.json
sudo restart docker
```

**Comment by markoa** [comment]
Closing as stale.
