### ISSUE TITLE
Optimize search results

### ISSUE THREAD

**Issue by fbrdaric** [semaphoreci/docs#263]
A potential user ended up being confused if elasticsearch or other technologies are supported in S2.

Ping account support team for more detailed explanation.

**Comment by markoa** [comment]
Another example would be, search for "caching" -> 
![screen shot 2019-01-03 at 4 29 06 pm](https://user-images.githubusercontent.com/8651/50645816-b5122900-0f74-11e9-9849-8cf8a0e2e1bb.png)

The Toolbox page is in many cases what you need (because it contains the cache CLI reference), but you wouldn't know it. It doesn't help that Help Scout doesn't show anything else but page title in search results.

**Comment by markoa** [comment]
Closing as stale.
