### ISSUE TITLE
Dedicated, high level page for MacOS building on Semaphore

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docs#299]
Basically, the page we get when we search for "mac" or "apple".

**Comment by markoa** [comment]
Instead of this, we'll start with two use case pages:
- iOS Continuous Integration
- MacOS Continuous Integration

Each will be based on a public demo project and follow the [common structure](https://docs.semaphoreci.com/article/99-rails-continuous-integration).

I'll open separate issues for each. This week I'll also start looking for someone to build the demo projects.
